#Nombre de la tarea
name:Testing

#En que accion se realiza
on:
    push:
        branches:
          - main

# Tarea a ejecutar
jobs:
  test-project:

    # En que sistema se ejecutará
    runs-on: ubuntu-latest

    #pasos de la tarea
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    # Instalar Python
      - name: Set up python
        uses: actions/setup-python@v2
        with:
            python-version: 3.x
    
    # Instalar dependencias
      - name: Install depedecias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements

    # Ejecturar Pruebas
      - name: Run Django unit tests
        run: |
          python manage.py test